name: main

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate.py
        run: python generate.py

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.py
          token: ${{ secrets.GITHUB_TOKEN }}
