name: main

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate.py
        run: python generator.py

      - name: Zip folders
        run: |
          for d in */; do zip -r "${d%/}.zip" "$d"; done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
